### ISSUE TITLE
Simpson's paradox in regression?

### ISSUE THREAD

**Issue by ZoologyDave** [jasonjb82/githubcollab#1]
@jasonjb82 Looks like there might be a problem in estimating the relationship. The figure created in the chunk code beginning in [[L50](https://github.com/jasonjb82/githubcollab/blob/d9564c4ff1dc33ccb34c69ab543e354d3e210103/docs/manuscript.Rmd#L50)]

Maybe fit three lines?

**Comment by jasonjb82** [comment]
Looks about right. I am about to leave for the field. Can you take care of it?
